//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_GeneralData
    {
        public int KeyID { get; set; }
        public Nullable<int> KeyTitle { get; set; }
        public string KeyValue { get; set; }
        public Nullable<int> Appointment_ID { get; set; }
    }
}
